// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYh2XnWi3yfEgPYub5ERaWTG8TfwVUomo',
    appId: '1:235134348511:web:f3fd6768cac51fc37b4d6a',
    messagingSenderId: '235134348511',
    projectId: 'quiz-f540d',
    authDomain: 'quiz-f540d.firebaseapp.com',
    storageBucket: 'quiz-f540d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOi0BNGc05clfy1Mgl8xIIwASXwhBHZ4Y',
    appId: '1:235134348511:android:9c18b8a5b17b0cfc7b4d6a',
    messagingSenderId: '235134348511',
    projectId: 'quiz-f540d',
    storageBucket: 'quiz-f540d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmvh_eB8HC6sviMZnJ4PAQm8fmh5c2d14',
    appId: '1:235134348511:ios:e596f9787722eef57b4d6a',
    messagingSenderId: '235134348511',
    projectId: 'quiz-f540d',
    storageBucket: 'quiz-f540d.appspot.com',
    iosClientId: '235134348511-oc9u06le8930rnenothf8gai46bucg4f.apps.googleusercontent.com',
    iosBundleId: 'com.example.trivia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmvh_eB8HC6sviMZnJ4PAQm8fmh5c2d14',
    appId: '1:235134348511:ios:d51fcaec3dd130607b4d6a',
    messagingSenderId: '235134348511',
    projectId: 'quiz-f540d',
    storageBucket: 'quiz-f540d.appspot.com',
    iosClientId: '235134348511-f413bkpc3p93kg1obaqkbammk4tnsrv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.trivia.RunnerTests',
  );
}
